%\VignetteIndexEntry{Bioconductor LaTeX Style}
%\VignettePackage{BiocStyle}
%\VignetteEngine{knitr::knitr}

\documentclass{beamer}

\usetheme{Boadilla}
\setbeamertemplate{footline}
{
  \leavevmode%
  \hbox{%
  \begin{beamercolorbox}[wd=.5\paperwidth,ht=2.25ex,dp=1ex,right,rightskip=1em]{section in head/foot}%
    \usebeamerfont{subsection in head/foot}\hspace*{2ex}\insertshorttitle
  \end{beamercolorbox}%
  \begin{beamercolorbox}[wd=.4\paperwidth,ht=2.25ex,dp=1ex,left,leftskip=1em]{subsection in head/foot}%
    \usebeamerfont{section in head/foot}\insertsectionhead\hspace*{2ex}
  \end{beamercolorbox}%
  \begin{beamercolorbox}[wd=.1\paperwidth,ht=2.25ex,dp=1ex,right]{date in head/foot}%
    \insertframenumber{} / \inserttotalframenumber\hspace*{2ex}
  \end{beamercolorbox}}%
  \vskip0pt%
}

\newcommand{\software}[1]{\textsl{#1}}
\newcommand\R{\software{R}}
%
\newcommand\Bioconductor{\software{Bioconductor}}
\newcommand{\Rpackage}[1]{\textsl{#1}}
\newcommand\Biocpkg[1]{%
  {\href{http://bioconductor.org/packages/#1}%
    {\Rpackage{#1}}}}
\newcommand\CRANpkg[1]{%
  {\href{http://cran.fhcrc.org/web/packages/#1/index.html}%
    {\Rpackage{#1}}}}
\newcommand{\Rcode}[1]{\texttt{#1}}
\newcommand{\Rfunction}[1]{\Rcode{#1}}
\newcommand{\Robject}[1]{\Rcode{#1}}
\newcommand{\Rclass}[1]{\textit{#1}}

\title{Training and Outreach in the \Bioconductor{} Project}
\author{Martin Morgan}
\institute[RPCI]{
  Roswell Park Cancer Institute\\
  Buffalo, NY, USA\\
  \href{mailto:martin.morgan@roswellpark.org}{martin.morgan@roswellpark.org}}
\date{3 November 2016}

\begin{document}

\maketitle

\section{Introduction}

\begin{frame}{Introduction}
  \begin{columns}
  \column{.5\textwidth}
  \includegraphics[width=.8\textwidth]{bioconductor_logo_rgb.eps}
  \bigskip\par
  \includegraphics[width=.15\textwidth]{Rlogo.png}
  \hspace{1em}
  \includegraphics[width=.3\textwidth]{nid61380-a1-rpci-cmyk-black.eps}
  \bigskip\par
  \href{https://bioconductor.org}{https://bioconductor.org}\par
  \href{https://support.bioconductor.org}{https://support.bioconductor.org}
  \column{.5\textwidth}
  Analysis and comprehension of high-throughput genomic data.
  \begin{itemize}
  \item Started 2002
  \item 1295 \R{} packages -- developed by `us' and user-contributed.
  \end{itemize}
  Well-used and respected.
  \begin{itemize}
  \item 43k unique IP downloads / month.
  \item 17,000 PubMedCentral citations.
  \end{itemize}
  \end{columns}
\end{frame}

\begin{frame}
  \includegraphics[width=\textwidth]{RStudio.png}
\end{frame}

\begin{frame}{Install, learn, use, develop}
  \begin{columns}
    \column{.6\textwidth}
    \includegraphics[width=\textwidth]{install-learn-use-devel.png}
    \column{.4\textwidth}
    Install\footnote[frame]{\url{https://bioconductor.org}}
    \begin{itemize}
    \item \R{}, \software{RStudio},
      \Bioconductor{}
    \end{itemize}
    Learn
    \begin{itemize}
    \item Courses, vignettes, workflows
    \end{itemize}
    Use
    \begin{itemize}
    \item Vignettes, manuals, support
      site\footnote[frame]{\url{https://support.bioconductor.org}}
    \end{itemize}
    Develop
  \end{columns}
\end{frame}

\begin{frame}{\Bioconductor{}}
  \begin{columns}
    \column{.4\textwidth}
    Learn \& use
    \begin{itemize}
    \item
      \textbf<1,2>{biocViews}\footnote[frame]{\url{https://bioconductor.org/packages/release}}
    \item \textbf<3>{Landing pages}\footnote[frame]{e.g.,
      \url{https://bioconductor.org/packages/edgeR}}
      \begin{itemize}
      \item Description
      \item Installation
      \item Documentation
      \end{itemize}
    \item \textbf<4-6>{Vignettes}\footnote[frame]{e.g.,
      \url{https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.pdf}}
    \item
      \textbf<7>{Workflows}\footnote[frame]{\url{http://bioconductor.org/help/workflows}},
      F1000
    \end{itemize}
    \column{.6\textwidth}
    \includegraphics<1>[width=.6\textwidth]{biocViews.png}
    \includegraphics<2>[width=.9\textwidth]{ChIPSeq-views.png}
    \includegraphics<3>[width=.9\textwidth]{edgeR-landing-page.png}
    \includegraphics<4>[width=.8\textwidth]{DESeq-vignette-1.png}
    \includegraphics<5>[width=.8\textwidth]{DESeq-vignette-2.png}
    \includegraphics<6>[width=.8\textwidth]{DESeq-vignette-3.png}
    \includegraphics<7>[width=.9\textwidth]{Workflows.png}
  \end{columns}
\end{frame}

\begin{frame}{Support site}
  \includegraphics[width=\textwidth]{support-site.png}
\end{frame}

\begin{frame}{Courses \& outreach}
  Activities
  \begin{itemize}
  \item Short (1 or 2 day)
  \item Extended (1 week)
  \item Conferences with `developer day' component
  \end{itemize}
  Third party
  \begin{itemize}
  \item MOOCs
  \item Workshops
  \end{itemize}
  Docker and AMIs available; AMIs used in short courses.
\end{frame}

\begin{frame}{What we don't do\ldots}
  \begin{itemize}
  \item Community-driven documentation
  \item Videos
  \item Ratings or recommendations
  \item \ldots
  \end{itemize}
  \ldots Partly because `more' does not seem to be the right answer
\end{frame}

\section{Acknowledgments}

\begin{frame}{Acknowledgments}
  Core team (current \& recent): Yubo Cheng, Valerie Obenchain, Herv\'e
  Pag\`es, Marcel Ramos, Lori Shepherd, Dan Tenenbaum, Greg Wargula.
  \medskip\par
  Technical advisory board: Vincent Carey, Kasper Hansen, Wolfgang
  Huber, Robert Gentleman, Rafael Irizzary, Levi Waldron, Michael
  Lawrence, Sean Davis, Aedin Culhane
  \medskip\par
  Scientific advisory board: Simon Tavare (CRUK), Paul Flicek
  (EMBL/EBI), Simon Urbanek (AT\&T), Vincent Carey (Brigham \&
  Women's), Wolfgang Huber (EBI), Rafael Irizzary (Dana Farber),
  Robert Gentleman (23andMe)
  \medskip\par
  Research reported in this presentation was supported by the National
  Human Genome Research Institute and the National Cancer Institute of
  the National Institutes of Health under award numbers U41HG004059
  and U24CA180996. The content is solely the responsibility of the
  authors and does not necessarily represent the official views of the
  National Institutes of Health.
\end{frame}

\end{document}
